### ISSUE TITLE
EE3 crash when using tablet

### ISSUE THREAD

**Issue by BeastOfTheLands** [pahimar/Equivalent-Exchange-3#956] opened 2015-07-15 20:17 UTC
I tried taking out some cobblestone from the tablet forgetting that it fills the inventory so i shift clicked with 4k exchange energy in the tablet and the game crashed.

Crash Report: http://pastebin.com/DVUVdTQ9

**Comment by utoc** [comment] 2015-07-16 21:45
This is likely a duplicate of https://github.com/pahimar/Equivalent-Exchange-3/issues/901

**Comment by pahimar** [comment] 2015-08-21 17:46
Closing in order to track issues on the unified ticket #992

**Closed by pahimar** 2015-08-21 17:46 UTC
Labels: bug, transmutation tablet
