### ISSUE TITLE
Dynamic EMC Suddenly Stops Calculating Midway

### ISSUE THREAD

**Issue by RoloEdits** [pahimar/Equivalent-Exchange-3#937] opened 2015-07-06 10:16 UTC
ill start off saying that there is very little information that i can give because i dont know where i should be looking for the problem.

the problem started after updating mods, about 20 or so, and after starting my world i was missing some items from my tablet so i looked at there emc and i was zero and from what i can gather when forcing ee3 to recalculate it gets hung up on something and doesn't get past the first "layer" so to speak like there values for wood but not planks, wood got calculated but planks didn't and from this i can only guess that certain raw resource items and produced items like cooked meat that are hard coded and the rest is calculated.

i tried downgrading each mod that i updated to the one i was using before when it was working and after doing all of them individually still no luck. its very strange that updating mods would cause something like this to happen so i started a new testing world one were i did not define anything at all
thinking it must be something i did to get it stuck but that wasn't the problem either because it still wasn't writing the values files, at least not until i exited the world but then upon examining the file it seems incomplete.

these are the file names of the mods that i updated and the one that i added

ThermalExpansion-[1.7.10]4.0.2B2-210

ThermalRecycling-1.7.10-0.4.2.5

ThaumicExploration-1.7.10-1.1-52

thaumicenergistics-0.8.10.6

StorageDrawers-1.7.10-1.5.10

RouterReborn-1.7.10-1.2.0.24-universal

neiaddons-1.12.10.34-mc1.7.10

magicbees-1.7.10-2.3.2

journeymap-1.7.10-5.1.0-unlimited

generators-0.9.15.91-mc1.7.10

gendustry-1.5.2.107-mc1.7.10

forestry_1.7.10-3.7.0.627-unstable

Fluxed-Crystals2-1.0.2

SuperEnchants-0.4.1  < -- added this one

compactmachines-1.7.10-1.20

Chisel2-2.4.1.40

buildcraft-7.0.13

Botania r1.6-198

Automagy-1.7.10-0.26

Aroma1997Core-1.7.10-1.0.2.14

ae2stuff-0.4.2.43-mc1.7.10

extrautilities-1.2.7.

PneumaticCraft-1.7.10-1.9.1-86-universal

off the top of my head the mods that integrate directly with ee3, as in a conscience reason as to why there is values to the mod or a manipulating of ee3  

AE2EE3Compat-1.0b2

Chisel2-2.4.1.40

EE3Help-2.2a

EquivalentEnergistics - 0.2 - 1.7.10

ImmersiveEngineering-0.3.3

extrautilities-1.2.7

PneumaticCraft-1.7.10-1.9.1-86-universal

Forbidden Magic-1.7.10-0.57

i should also mention that some of the ae2 ee3 compat values get calculated such as the ores,certus, singularity but nothing else has values 

while pneumatic craft and extra utilities don't have any values

and chisel 2 has a majority of values there
 
if you would like me to explain it again maybe differently, like in response to questions , i can explain it better

please ask don't hesitate to ask

**Comment by AstralSorcerer** [comment] 2015-07-06 15:40
I think I had the same issue (#925).  Chisel 2 added EE3 integration in version 2.4.0, and for me at least, it seems to be causing a NullPointerException in DynEMC thread, preventing EMC values from getting calculated for most items.  I haven't tested with Chisel 2.4.1, but it doesn't look like they fixed it in the new version.

**Comment by RoloEdits** [comment] 2015-07-07 00:08
even after downgrading to Chisel2-2.3.10.37 it still not calculating the values. may i ask how you see the DynEMC thread error? was it a crash log?and were can i find it? and i believe if i remember correctly that i was using Chisel2-2.4.0.38 before and was working correctly but maybe i was just seeing values on stuff i looked for and used frequently so i may be mistaken

**Comment by RoloEdits** [comment] 2015-07-07 00:30
after looking at the fml-client-latest i discovered that it looks like most of cofh mods are adding some type of support and this support i believe wasn't there before and may be the cause of the problem 
i did try downgrading all of the cofh mod like redstone arsenal foundation core dynamics and expansion but they remove all of the beta build that i had working just fine

ill just paste a few things here as i do not want to clutter the page



[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: EnergyValueRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added a pre-assignment energy value of 128.0 for object 1xitemStack[item.thermalfoundation.material.ingotCopper@64]
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: EnergyValueRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added a pre-assignment energy value of 192.0 for object 1xitemStack[item.thermalfoundation.material.ingotTin@65]
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: EnergyValueRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added a pre-assignment energy value of 1024.0 for object 1xitemStack[item.thermalfoundation.material.ingotNickel@68]
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: EnergyValueRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added a pre-assignment energy value of 512.0 for object 1xitemStack[item.thermalfoundation.material.ingotLead@67]
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: EnergyValueRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added a pre-assignment energy value of 512.0 for object 1xitemStack[item.thermalfoundation.material.ingotSilver@66]
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: EnergyValueRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added a pre-assignment energy value of 16384.0 for object 1xitemStack[item.thermalfoundation.material.ingotPlatinum@69]
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: EnergyValueRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added a pre-assignment energy value of 16384.0 for object 1xitemStack[item.thermalfoundation.material.ingotMithril@70]
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: EnergyValueRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added a pre-assignment energy value of 1536.0 for object 1xitemStack[item.thermalfoundation.material.rodBlizz@1024]
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: RecipeRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added recipe (Output: 4xitemStack[item.thermalfoundation.material.dustSignalum@42], Inputs: 1xitemStack[item.thermalfoundation.material.dustCopper@32] 1xitemStack[item.thermalfoundation.material.dustCopper@32] 1xitemStack[item.thermalfoundation.material.dustCopper@32] 1xitemStack[item.thermalfoundation.material.dustSilver@34] 1000xfluidStack.redstone)
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: RecipeRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added recipe (Output: 4xitemStack[item.thermalfoundation.material.dustLumium@43], Inputs: 1xitemStack[item.thermalfoundation.material.dustTin@33] 1xitemStack[item.thermalfoundation.material.dustTin@33] 1xitemStack[item.thermalfoundation.material.dustTin@33] 1xitemStack[item.thermalfoundation.material.dustSilver@34] 1000xfluidStack.glowstone)
[16:55:48] [Client thread/TRACE] [Equivalent Exchange 3/ThermalFoundation]: RecipeRegistry[INITIALIZATION]: Mod with ID 'ThermalFoundation' added recipe (Output: 4xitemStack[item.thermalfoundation.material.dustEnderium@44], Inputs: 1xitemStack[item.thermalfoundation.material.dustTin@33] 1xitemStack[item.thermalfoundation.material.dustTin@33] 1xitemStack[item.thermalfoundation.material.dustSilver@34] 1xitemStack[item.thermalfoundation.material.dustPlatinum@37] 1000xfluidStack.ender)



these are not values that i pick when i assigned them myself until they did so i can only assume this means there adding them

i see similar looking things for mods that add emc support 


AE2 E33 Compat [Client thread/TRACE] [Equivalent Exchange 3/ae2ee3emcaddon]: EnergyValueRegistry[PREINITIALIZATION]: Mod with ID 'ae2ee3emcaddon' added a pre-assignment energy value of 64.0 for object 1xitemStack[tile.appliedenergistics2.BlockSkyStone@0]


Pneumatic Craft [Equivalent Exchange 3/PneumaticCraft]: EnergyValueRegistry[PREINITIALIZATION]: Mod with ID 'PneumaticCraft' added a pre-assignment energy value of 16.0 for object 1xitemStack[item.plasticPlant2@2]

**Comment by RoloEdits** [comment] 2015-07-07 00:35
thinking back on maybe they were adding support in the beta version and i just mistook it for something else. i have grow able ores in my mods and to get the ingot you put the droppings of the ore reed just like a chest or furnace and i thought that was calculating to a different number then i specified so i could have just over looked any differences as something along those lines

**Comment by RoloEdits** [comment] 2015-07-07 00:48
after finding ee3 info in the fml-client-latest i rean ee3 helper's command /ee3h regen to for DynEMC and i found and error when looking at it

[17:43:01] [DynamicEMC Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IllegalArgumentException: Multiple entries with same key: 1000xfluidStack.oil=[[1xitemStack[item.oilBucket@0]]] and 1000xfluidStack.oil=[[1xitemStack[item.for.waxCapsuleOil@0]], [1xitemStack[item.for.refractoryOil@0]], [1xitemStack[item.for.canOil@0]], [1xitemStack[item.bucketOil@0]]]

this is just one line but  believe this might be the problem ill have to look for the multiple entrys to find out more

**Comment by AstralSorcerer** [comment] 2015-07-07 02:33
That's not the error I was getting.  I got a NullPointerException in the DynEMC thread.

**Comment by RoloEdits** [comment] 2015-07-07 02:42
i don't think its chisel that's the problem for me i even tried completely removing it and it still wasn't working

**Comment by RoloEdits** [comment] 2015-07-07 02:43
the only error i seem to be getting from what i can gather at least is the oil one

**Comment by AstralSorcerer** [comment] 2015-07-07 03:23
I got the same error with the latest CoFHCore/ThermalFoundation/etc.  It seems that there is more than one way to break DynEMC.

**Comment by RoloEdits** [comment] 2015-07-07 03:26
so it would seem

**Comment by RoloEdits** [comment] 2015-07-07 04:16
im not 100% sure or even 10% sure but i think the problems because pneumatic craft also has oil and fuel along with buildcraft. there dictionaried together and i think ee3 has a problem with any dictionary when there different values for an entire ore or fluid dictionary if that makes any sense 

like if i change the value of the industrial diamond its still ok but if i add multiple entries for ore:gemDiamond one at say the normal and one at half i believe you would get an error

this was bound to happen eventually with mods when they add values for there own stuff on top of what may be there already

do you have pneumatic craft installed?

**Comment by AstralSorcerer** [comment] 2015-07-07 04:37
I do.  And I think i get what you are saying.

**Comment by RoloEdits** [comment] 2015-07-07 05:02
after removing pneumatic craft for aditional testong i get an error 

[22:00:31] [DynamicEMC Thread/INFO] [Equivalent Exchange 3/]: Beginning dynamic value computation
[22:00:33] [DynamicEMC Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException

**Comment by RoloEdits** [comment] 2015-07-07 05:03
and its still stuck calculating as one would expect

**Comment by AstralSorcerer** [comment] 2015-07-07 05:08
Can you post the following few lines?  That might be the issue I was having with Chisel.

**Comment by RoloEdits** [comment] 2015-07-07 05:12
thats actually all there was, directly after this line was an inventory tweaks update that im viewing my inventory

**Comment by RoloEdits** [comment] 2015-07-07 05:12
ill try downgrading chisel again to see if that fixes the problem

**Comment by RoloEdits** [comment] 2015-07-07 05:23
ok after downgrading to Chisel2-2.3.10.37 and removing pneumatic craft the values calculated fully, at least as far as i can tell

**Comment by AstralSorcerer** [comment] 2015-07-07 05:35
I can confirm that it was a chisel item (the marble pillar with metadata 0, to be precise) that was entered into the energy value map with a null energy value.  I'm not sure whether or not Chisel is at fault.

**Comment by RoloEdits** [comment] 2015-07-07 05:43
has it been told to the chisel dev yet?

**Comment by AstralSorcerer** [comment] 2015-07-07 05:49
I reported the issue, but like I said, I'm not 100% sure that it is actually Chisel's fault.

**Comment by RoloEdits** [comment] 2015-07-07 05:50
yah just as long as he knows

**Comment by RoloEdits** [comment] 2015-07-07 05:51
and also out of context but after updating all the cofh stuff does you blaze power texture look weird?

**Comment by AstralSorcerer** [comment] 2015-07-07 06:06
Yes.

**Comment by RoloEdits** [comment] 2015-07-07 06:08
I guess i should report it

**Comment by AstralSorcerer** [comment] 2015-07-07 06:11
It might be intentional.  I kind of like the idea of an animated blaze powder texture actually.

**Comment by RoloEdits** [comment] 2015-07-07 06:11
yours is animated?

**Comment by AstralSorcerer** [comment] 2015-07-07 06:15
Yes.

**Comment by RoloEdits** [comment] 2015-07-07 06:18
![2015-07-06_23 08 26](https://cloud.githubusercontent.com/assets/12489689/8539886/5ca940ce-2435-11e5-8393-23a383894db3.png)

**Comment by RoloEdits** [comment] 2015-07-07 06:21
mine just looks like this

**Comment by AstralSorcerer** [comment] 2015-07-07 06:25
Wierd.

**Comment by RoloEdits** [comment] 2015-07-07 06:29
yah i guess it on my end of things ill try to track it down but im not good at finding this kind of stuff its just a texture so it doesn't bother me tooo much

**Comment by RoloEdits** [comment] 2015-07-07 06:33
its made up of a bunch of icons

![2015-07-06_23 32 40](https://cloud.githubusercontent.com/assets/12489689/8540117/6b0851a8-2437-11e5-94cc-2c0aa5ba9d95.png)

**Comment by AstralSorcerer** [comment] 2015-07-07 06:36
I think that is the entire texture map.  I don't know much about Minecraft rendering, but I believe that it makes a single sheet out of every texture in the game, and passes coordinates within that sheet to OpenGL in order to use a specific texture.  I believe that you are looking at that sheet, which would mean that incorrect coordinates are being passed (I think).

**Comment by RoloEdits** [comment] 2015-07-07 06:37
it would make sense

**Comment by RoloEdits** [comment] 2015-07-07 06:38
i have a similar problem with ender tech pads

**Comment by AstralSorcerer** [comment] 2015-07-07 06:39
Are you using a texture pack?

**Comment by RoloEdits** [comment] 2015-07-07 06:39
yah unity

**Comment by RoloEdits** [comment] 2015-07-07 06:40
ill try with default

**Comment by RoloEdits** [comment] 2015-07-07 06:41
nope still wonky

**Comment by AstralSorcerer** [comment] 2015-07-07 06:43
Strange.

**Comment by DoughnutDev** [comment] 2015-07-07 18:11
My EMC isnt working either but if you look in my log it registers every EMC value from all the mods, but in-game it does not work. but in singleplayer it works fine...

**Comment by AstralSorcerer** [comment] 2015-07-07 18:31
Can I see your log?

**Comment by DoughnutDev** [comment] 2015-07-07 20:25
https://www.dropbox.com/s/paaoraz6gg6039p/fml-server-latest.log?dl=0

**Comment by AstralSorcerer** [comment] 2015-07-07 23:22
That looks like the issue that @RoloEdits was having.  I think that might have started happening with the latest update to the CoFH mods.

**Comment by RoloEdits** [comment] 2015-07-07 23:48
yes it seems like a temporary workaround is to either turn off ee3 support from the TE config or to remove another mod that's its conflicting with for example i removed pneumatic craft.

**Comment by RoloEdits** [comment] 2015-07-08 00:04
and for right now if your not handing the ordict item like ingotTin or ingotCopper's values then most of the stuff doesn't work anyways almost all of the gears have no values but if you dis then ee3 now supports there crafting handler so if you assign a value to the tesseract frame then the full and real tesserract have values dynamically. i had to assign values manually because of all the problems with glass im having messing up value not calculating. but some thing are still a bit wonky like things,for me at least, with invar don't calculate.

**Comment by DoughnutDev** [comment] 2015-07-08 00:17
I just gave up on EE3 I am going to wait tell it is working right.

**Comment by jermangarc** [comment] 2015-08-06 20:46
I think I might be having a related issue after reading all of this thread. I updated to the latest COFHCore/TE and now my world gets stuck on loading. It stops immediately after DynamicEMC system initializes. It just sits there doing nothing, nothing shows up on screen and it doesn't crash out or anything.

**Comment by pahimar** [comment] 2015-08-21 17:26
Closing in order to track issues on the unified ticket #990

**Closed by pahimar** 2015-08-21 17:26 UTC
Labels: bug, dynamic emc
