### ISSUE TITLE
Chalk Circle Still Does Not Resize

### ISSUE THREAD

**Issue by viktro78** [pahimar/Equivalent-Exchange-3#994] opened 2015-08-25 21:47 UTC
Yep Me again. The Chalk Circle continues to be unable to reduce in size. My charge keybinding is set to V set Shift+V does not work. Seems to be stuck permanently at 5x5. I have even reinstalled the mod entirely to no evail. Can't wait to try it out though :).

**Comment by pahimar** [comment] 2015-08-25 21:53
Duplicate of https://github.com/pahimar/Equivalent-Exchange-3/issues/981. Please refrain from opening new tickets - just add more comments to the existing ticket and we can reopen it if it warrants.

**Closed by pahimar** 2015-08-25 21:53 UTC
