### ISSUE TITLE
Using latest build crashes game on world load.

### ISSUE THREAD

**Issue by AnAverageHuman** [pahimar/Equivalent-Exchange-3#941] opened 2015-07-07 18:33 UTC
I cloned the repository, then set up the workspace according to README.md. Running `gradle build` gives me a .jar with an md5sum of 8a70c06425ad72e79b9228f44f0123c2.

Upon loading any world, I get the following error:

> Description: Ticking memory connection

> java.lang.NullPointerException: Ticking memory connection
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

The rest of the crash log can be found [here](http://pastebin.com/raw.php?i=CWSwgWX9).

The issue also occurs if there are no other mods being loaded.

**Comment by pahimar** [comment] 2015-07-07 18:44
I need the fml log not the crash log

**Comment by AnAverageHuman** [comment] 2015-07-07 18:59
Contents of latest.log:

    [14:56:56] [Server thread/ERROR]: Encountered an unexpected exception
    net.minecraft.util.ReportedException: Ticking memory connection
    	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
    	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
    	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
    Caused by: java.lang.NullPointerException
    	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:?]
    	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
    	... 5 more
    [14:56:56] [Server thread/ERROR]: This crash report has been saved to: /mnt/Jeffrey/games/Minecraft/Technic/technic/modpacks/echoreply/crash-reports/crash-2015-07-07_14.56.56-server.txt
    [14:56:56] [Server thread/INFO]: Stopping server
    [14:56:56] [Server thread/INFO]: Saving players
    [14:56:56] [Server thread/INFO]: Saving worlds
    [14:56:56] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
    [14:56:57] [Client thread/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@94b00e1[id=cd6c60c7-17dc-4548-8560-857f48f10115,name=jeffreylin_,properties={},legacy=false]
    com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
    	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
    	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [YggdrasilMinecraftSessionService.class:?]
    	at ichun.common.core.EntityHelperBase.getFullGameProfileFromName(EntityHelperBase.java:109) [EntityHelperBase.class:?]
    	at morph.common.morph.MorphState.createPlayer(MorphState.java:173) [MorphState.class:?]
    	at morph.common.morph.MorphState.readTag(MorphState.java:123) [MorphState.class:?]
    	at morph.common.packet.PacketMorphStates.handleClient(PacketMorphStates.java:83) [PacketMorphStates.class:?]
    	at morph.common.packet.PacketMorphStates.execute(PacketMorphStates.java:62) [PacketMorphStates.class:?]
    	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) [ChannelHandler$PacketExecuter.class:?]
    	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) [ChannelHandler$PacketExecuter.class:?]
    	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061) [bao.class:?]
    	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
    	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    [14:56:57] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@94b00e1[id=cd6c60c7-17dc-4548-8560-857f48f10115,name=jeffreylin_,properties={},legacy=false]
    com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
    	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
    	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [YggdrasilMinecraftSessionService.class:?]
    	at net.minecraft.client.resources.SkinManager$3.run(SourceFile:106) [brm.class:?]
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45-internal]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45-internal]
    	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by AnAverageHuman** [comment] 2015-07-07 19:07
Seems like it works if all other mods are removed. Probably not EE3 related.

**Comment by wasweb** [comment] 2015-07-12 09:30
It IS EE3 related: http://pastebin.com/gHX40C3W (prior log to crash). Works fine before: https://github.com/pahimar/Equivalent-Exchange-3/commit/e4c61830831d4cbf7c2e2d843bc692aca3c51f98

**Comment by IntelliSun** [comment] 2015-07-12 10:37
@wasweb your issue seems to unrelated, as it occurs during player login. @AnAverageHuman issue seems to occur during server initialization, please open a new issue to help tracking.

**Comment by wasweb** [comment] 2015-07-12 14:25
I got te same crash report as @AnAverageHuman. He also states that he got the crash during world loading, as in my case. @pahimar wanted an an fml log to see what heppend before the crash. Here it is.. btw. The issue's title "Using latest build" refers to the same version that I used when I got the crash.(imho)

**Comment by wasweb** [comment] 2015-07-12 20:57
Duplicate of #918

**Comment by pahimar** [comment] 2015-08-21 19:54
Tracking issue on #918

**Closed by pahimar** 2015-08-21 19:54 UTC
