### ISSUE TITLE
Minium stone transmutation tablet crash.

### ISSUE THREAD

**Issue by NolanSyKinsley** [pahimar/Equivalent-Exchange-3#848] opened 2015-05-10 04:13 UTC
I made a minium stone not knowing it wouldn't work, so I went to transmute it in the tablet. I shift click the minium stone in and when I clicked to transmute it  locks up the client solid with no error at all.

Placing the minium stone in any slot other than the center slot where it goes when shift clicked does not cause a lockup.

**Comment by pahimar** [comment] 2015-05-10 17:00
Not an issue specifically with the Transmutation Tablet, the issue here is with Shift Clicking an item out of the tablet

**Comment by MrPotatoGaming** [comment] 2015-06-28 16:19
I found this post after reproducing the issue, and while you've noted it, I have a question:
When you shift click the minium stone into the Transmutation Tablet, it fills the middle slot. Which, no other items can go into, this leads me to assume the middle slot is the same general idea as the "Klein Star" slot back in EE2. However, the crashing isn't caused upon shift-clicking the Minium Stone out of the table, only when trying to transmute.  I also get the client lockup issue, I have even tried using minecraft's forced crash (f3+c for 10 seconds) but that didn't help either. 

Now, my question is kinda based on the earlier assumption, is the crash caused by the tablet trying to reduce the EMC value of the Minium Stone?

**Comment by pahimar** [comment] 2015-08-21 17:47
Closing in order to track issues on the unified ticket #992

**Closed by pahimar** 2015-08-21 17:47 UTC
Labels: bug, transmutation tablet
