### ISSUE TITLE
"Fatal error has occured, this connection is terminated" on SP world load

### ISSUE THREAD

**Issue by CatDany** [pahimar/Equivalent-Exchange-3#807] opened 2015-05-04 15:39 UTC
I tried this on 495 and 465 builds
465 build log http://pastebin.com/HwU1fuuM
495 build log http://pastebin.com/hSEiYWMD
http://i.imgur.com/g6AAfCr.png

**Comment by CatDany** [comment] 2015-05-04 15:47
Seems like ComputerCraft incompat bug. Wireless modem in the recipe of a turtle has a wrong EMC or something

**Comment by CatDany** [comment] 2015-05-04 15:48
Works fine without CC/OpenPeripherals

**Comment by Alklaine** [comment] 2015-05-04 23:58
Agreed, similar log here (afflicted area of world load: http://pastebin.com/GvrEnmCf), Computer Craft seems to be the breaking point with Energy Values.
Full log exceeds post size limit unfortunately.

**Comment by CatDany** [comment] 2015-05-05 09:04
I tried looking at the code, but I'm bad at reading other people's code, and I don't know how you've done EMC calculation and syncing, but it seems like JSON that's been sent to the client is broken somewhere, maybe a JSON syntax symbol in an item name?

**Comment by Wulfson** [comment] 2015-05-06 14:11
This looks like a dupe of #803

**Comment by pahimar** [comment] 2015-05-06 14:22
Dupe of #803

**Closed by pahimar** 2015-05-06 14:22 UTC
