### ISSUE TITLE
Can't Create Chalk

### ISSUE THREAD

**Issue by LinkzZ97** [pahimar/Equivalent-Exchange-3#1110] opened 2016-09-21 03:20 UTC
put the ingredients to make chalk in crafting table.

**Comment by pahimar** [comment] 2016-09-21 17:44
Can you supply one of the log files specified above? It helps identify what other mod interactions are going on so that we can troubleshoot further.

On it's own EE3 0.3.0.547 has a working chalk recipe, so I suspect you are having a mod interaction that is suppressing the recipe.

**Comment by jasoncarrete5** [comment] 2016-10-14 23:38
Try putting clay in the top left slot and bone meal in the middle left slot. The wiki says the recipe for chalk is different.
![capture](https://cloud.githubusercontent.com/assets/6133706/19405470/c8a4d322-9245-11e6-9389-d6289b2c66e2.PNG)

**Comment by pahimar** [comment] 2016-10-25 18:46
It's been over a month since @LinkzZ97 reported this issue, and over a month since I asked for more info. In the absence of any usable debug information I'm going to close this issue as not reproducible.

**Closed** 2016-10-25 18:46 UTC
