### ISSUE TITLE
Shift clicking items out of transmutation tablet causes server crashes 

### ISSUE THREAD

**Issue by whitepyros** [pahimar/Equivalent-Exchange-3#979] opened 2015-08-13 01:47 UTC
Whenever players shift click more then a stack of items out of a transmutation tablet the server crashes
I have tested and the same thing can happen on single player too but it doesnt always happen
http://pastebin.com/vk6Lx02a

**Comment by Wulfson** [comment] 2015-08-13 14:19
Probably a dupe of #975 #956 and #901

**Comment by pahimar** [comment] 2015-08-21 17:46
Closing in order to track issues on the unified ticket #992

**Closed by pahimar** 2015-08-21 17:46 UTC
Labels: bug, transmutation tablet
