### ISSUE TITLE
Extra Utilities Integration w/ Equivalence Exchange

### ISSUE THREAD

**Issue by porteriscool** [pahimar/Equivalent-Exchange-3#912] opened 2015-06-11 19:14 UTC
When using both equivalent exchange 3 and extra utilities in the same mod pack together, there is a likely chance that the equivalent exchange algorithm will break because of the implemented wood, stone, lapis, and redstone colored blocks having no value to them as they can be used again in the wood, stone, lapis, redstone, etc. colored blocks recipes. To fix this, maybe adding pre-set values to the blocks will not break the algorithm. By the way, it might not even be a problem within Extra Utilities. It might be a problem with the algorithm in Equivalence Exchange, where this could also be added to the problem where items that are ore dict. don't have values. Either or, this problem should be something that needs to be resolved, and I just thought about bringing this issue up.

**Comment by Wulfson** [comment] 2015-06-11 19:30
Dupe of #828, among other tickets...

**Comment by porteriscool** [comment] 2015-06-11 19:40
Okay thank you for the information, did not know if it was known or not, but at least it is.

**Comment by pahimar** [comment] 2015-06-11 20:18
Duplicate

**Closed by pahimar** 2015-06-11 20:18 UTC
