### ISSUE TITLE
Dynic Emc OreDictionary Issues

### ISSUE THREAD

**Issue by Unknown-88** [pahimar/Equivalent-Exchange-3#829] opened 2015-05-08 00:35 UTC
Let's take a build craft tank for example, it is not given an emc value because some glass items that CAN be used to craft it don't have emc values. Prehapse ignore those?

**Comment by pahimar** [comment] 2015-05-08 12:23
It does, if you check the algorithm. This has to do with items belonging to more than one OreDictionary entry and those entries having disparate items in them. OreDictionary items are not always equivalent so there is some special casing there.

It's part of a problem with ExtraUtils that I still need to sort out.

**Comment by pahimar** [comment] 2015-05-08 12:24
Duplicate of #829

**Closed by pahimar** 2015-05-08 12:24 UTC
