### ISSUE TITLE
Player Knowledge Lost After Existing World and Re-Joining

### ISSUE THREAD

**Issue by SwatKid** [pahimar/Equivalent-Exchange-3#945] opened 2015-07-09 00:58 UTC
Just as the title suggests. I have looked at all ee3 related stuff and it seems that everything has been wiped. i am using version 507.

**Comment by Lomeli12** [comment] 2015-07-09 03:52
Also been having this issue on my server. A person on my server also crashes when checking their tome after losing their knowledge.

**Comment by SwatKid** [comment] 2015-07-09 05:16
I never got kicked, but after spending a couple hours getting a emc machine going and getting all needed items learned to just lose it after i went for a break really stinks.

**Comment by RoloEdits** [comment] 2015-07-09 09:01
been happening to me just recently and just now after crashing because a TE problem and after joining back i found out i had lost a lot of stuff i had learned

**Comment by RoloEdits** [comment] 2015-07-09 09:22
after examining closer from what i remember(i learned a lot of stuff) it seems like it forgot everything after a certain time like i logged in after getting ee3 up and running yesterday i started teaching it all the things and it was fine, then after playing for about an hour or so without logging out or in between that time  i crashed  and it forgot all the stuff i taught it.

i remember before the knowledge loss, at least to me, would happen every time i crashed before 507 was released.

i think this may be a similar issue to what was causing that to happen.

another problem i had is where i believe when running ee3 Helper's command to force dynEmc in game is i think its re-saving the file before a lot of stuff can be recalculated so i have all my preassigned things still taught, because that doesn't get updated when running dynEmc those values are just used for  calculating other things if needed, and the few things that got calculated.

if that makes any sense...
so you may not want to use that command if you have it it may cause problems.

**Comment by RoloEdits** [comment] 2015-07-09 10:25
i think i found another issue that's probably related to this problem, when teaching things to my tome after teaching it something i'm able to put the same item in again and instead of saying i have already learned this it just eats it and when looking at my knowledge in the tablet it briefly shows multiples of the item and then one disappears .

there may be a problem of the updating or checking of the transmutations file.

**Comment by IntelliSun** [comment] 2015-07-10 11:05
This issue become a bit of mess, if you have more issues to report please open new ones, this is not a support forum, please keep everything in place to make it easy to track.

About the knowledge problem, it's hard to say what exactly the problem is as Pahimar does not tag releases, though I spotted some movement in data files as of recent commits.

**Comment by RoloEdits** [comment] 2015-07-10 12:41
ok i will from now on i apologize. i'm just hesitant to make a bunch of new reports.hate to be "that guy" if you know what i mean.

**Comment by pahimar** [comment] 2015-08-21 17:03
Closing in order to track issues on the unified ticket #989

**Closed by pahimar** 2015-08-21 17:03 UTC
Labels: bug, knowledge system
