### ISSUE TITLE
Crashes with 0.3.504

### ISSUE THREAD

**Issue by Cooolaid** [pahimar/Equivalent-Exchange-3#833] opened 2015-05-08 03:30 UTC
I updated the mod from 0.3.502 to 0.3.504 and got a immediate crash in the launcher while console was progressing minecraft.

When I go back to 0.3.502 - everything works fine.

http://pastebin.com/fFuq3KAs

**Comment by pahimar** [comment] 2015-05-08 11:45
Duplicate of #827

**Closed by pahimar** 2015-05-08 11:45 UTC
