### ISSUE TITLE
Known transmutations not being saved

### ISSUE THREAD

**Issue by Robindino17** [pahimar/Equivalent-Exchange-3#1104] opened 2016-08-09 19:37 UTC
So did some digging around the internet and found that an exact same issue happened around 2015 september, on horizons daybreaker server exact same thing is happening,
I research something, I log off and when I log back on it doesnt save.

**Comment by spannerman79** [comment] 2016-08-10 07:39
https://github.com/pahimar/Equivalent-Exchange-3/issues/989#issuecomment-177364941

**Comment by Robindino17** [comment] 2016-08-11 12:50
Yeah thats the ticket I read, any idea why this is popping up again?

**Comment by pahimar** [comment] 2016-08-11 12:59
I'm going to need some basic information before we can understand what is going on. Things like;

1) Minecraft version
2) Minecraft Forge version
3) Version of Equivalent Exchange 3 you are using
4) A fml-latest-client log for a play session in which this behaviour occurs (the whole log, not just snippets. Use something like pastee or pastebin)
5) Your player knowledge json file

**Comment by spannerman79** [comment] 2016-08-11 14:07
@pahimar the issue is that [FTB Horizons: Daybreaker](https://www.feed-the-beast.com/projects/ftb-horizons-daybreaker/files/2259609) contains What Is Its EMC - specifically [this](https://minecraft.curseforge.com/projects/what-is-its-emc/files/2245296) version.

It was already reported but the issue was just closed - See https://github.com/Lomeli12/WIIEMC/issues/2

This follows along the issue and comment that I linked before.

**Comment by pahimar** [comment] 2016-08-11 18:22
Ok, so it's not an issue here. Good to know.

Closing.

**Closed by pahimar** 2016-08-11 18:22 UTC

**Comment by MexRex** [comment] 2016-10-19 20:30
Greetings, 

Look at that cool stuff!  I  think this is what you are looking for, check it out <http://straight.telltaleheart.us/e8uuk>


SHoCKYCooKIE

**Comment by MexRex** [comment] 2016-10-19 20:31
Hey, 

Take a  look at  that information please,  it seems to be very  useful.  Have  you already heard something about that? Just  check it out <http://busy.mi-educacion.com/e8tzo>

In haste, SHoCKYCooKIE

**Comment by MexRex** [comment] 2016-10-25 18:16
Hi! 

I've had a nice  day today  and wanted  to share this with you, check  it out <http://apply.cgraphix.net/e8hwsp>


Sincerely yours, shockycookie
